### ISSUE TITLE
Admin Logs [Client]

### ISSUE THREAD

**Issue by KSJDiamondGaming** [GitMocha/Mocha-Logs#3]
![image](https://user-images.githubusercontent.com/83096833/227985058-494770cf-d9a0-486e-9fa2-7f0f95f87e86.png)

![image](https://user-images.githubusercontent.com/83096833/227985250-56576cd2-5c06-4fe9-9be0-c172d6968733.png)

Receiving these errors

**Comment by GitMocha** [comment]
Update your qb-admin using the qb-admin repo and then add the logs. Should be fine since all were fully tested before release. On the latest versions.

**Comment by KSJDiamondGaming** [comment]
![image](https://user-images.githubusercontent.com/83096833/228344521-78f141c2-f873-46dc-8470-1f1e3f0ee42b.png)


![image](https://user-images.githubusercontent.com/83096833/228344544-4f112766-193c-4218-97e8-395a694ea491.png)


Previosu issues have been resolved so thankyou for the above. A new one has occured around the abouve lines when "freezing" a player. compared with logs i cant see differences

**Comment by GitMocha** [comment]
Follow the instructions laid out in each lua file. There's no reason to get that error unless you haven't correctly copied each part.
